# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile

development:
 adapter: mysql2
 encoding: utf8
 database: fibair_development
 host: 127.0.0.1
 pool: 5
 username: fibair
 password: fibair 
 